/** Shape of public/orig/data.json (generated by tools/swf/build-data.mjs from the original SWF). */
export type Op =
  | ['stop']
  | ['goto', number]
  | ['gotoRandom', number]
  | ['hit']
  | ['rhit']
  | ['shoot']
  | ['remove']
  | ['randLabel', string, number]
  | ['stopRandom', number, number]
  | ['rootPlay'];

export interface Matrix {
  a: number;
  b: number;
  c: number;
  d: number;
  tx: number;
  ty: number;
}
export interface Box {
  x0: number;
  x1: number;
  y0: number;
  y1: number;
}

export interface ClipData {
  id: number;
  n: number;
  labels: Record<string, number>;
  ops: Record<string, Op[]>;
  snd: Record<string, number[]>;
  m?: Matrix;
}

export interface UnitData {
  id: number;
  A: number;
  states: Record<string, ClipData & { m: Matrix }>;
  shadow: { id: number; m: Matrix } | null;
  hit: Box;
}

export interface TurretData {
  id: number;
  clip: ClipData;
  m: Matrix;
  extra: { id: number; m: Matrix }[];
}

export interface OrigData {
  fps: number;
  stage: { w: number; h: number };
  /** [name, cost, trainFrames] (index 0 unused) */
  EN: ([string, number, number] | string)[];
  /** [name, price, ?] */
  TU: ([string, number, number] | string)[];
  /** [shootSpeed, bulletId, damage, range] */
  TS: (number[] | string)[];
  /** [health, melee damage, ranged damage, melee range, shoot range] */
  ES: (number[] | string)[];
  EV: number[];
  units: (UnitData | null)[];
  turrets: (TurretData | null)[];
  bases: { base1: { x: number; y: number; hit: Box }; base2: { x: number; y: number; hit: Box } };
  sounds: Record<string, string>;
  fonts: Record<string, string>;
  texts: Record<string, unknown>;
}

export type Side = 1 | 2;

export type Cmd =
  | { t: 'tray'; id: number }
  | { t: 'cancel'; i: number }
  | { t: 'turret'; spot: number; id: number }
  | { t: 'sell'; spot: number }
  | { t: 'addon' }
  | { t: 'evolve' }
  | { t: 'special' };

/** things the renderer / audio react to; the simulation itself never reads them back */
export type Ev =
  | { k: 'part'; id: number; x: number; y: number; params: number[] }
  | { k: 'snd'; id: number; x: number }
  | { k: 'shake'; amount: number }
  | { k: 'cash'; side: Side; x: number; y: number; amount: number }
  | { k: 'unit'; uid: number; id: number; side: Side }
  | { k: 'end'; winner: Side };
